"""add_credits_remaining_fixed

Revision ID: 431230c7b844
Revises: dee29a6538d6
Create Date: 2025-12-19 11:42:50.833533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431230c7b844'
down_revision: Union[str, None] = 'dee29a6538d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits_remaining', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credits_remaining')
    # ### end Alembic commands ###
