"""Add password reset tokens table

Revision ID: 93b9dd446b00
Revises: dfc767a39b9b
Create Date: 2026-01-11 06:12:32.215318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93b9dd446b00'
down_revision: Union[str, None] = 'dfc767a39b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proxy_logs_id'), table_name='proxy_logs')
    op.drop_index(op.f('ix_proxy_logs_timestamp'), table_name='proxy_logs')
    op.drop_table('proxy_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxy_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action', postgresql.ENUM('ALLOWED', 'BLOCKED_OPA', 'BLOCKED_DLP', 'REDACTED', name='proxyaction'), autoincrement=False, nullable=True),
    sa.Column('risk_score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('findings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('proxy_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('proxy_logs_pkey'))
    )
    op.create_index(op.f('ix_proxy_logs_timestamp'), 'proxy_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_proxy_logs_id'), 'proxy_logs', ['id'], unique=False)
    # ### end Alembic commands ###
