"""Add last_credit_reset

Revision ID: dfc767a39b9b
Revises: 431230c7b844
Create Date: 2025-12-22 09:44:06.776030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc767a39b9b'
down_revision: Union[str, None] = '431230c7b844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed server_default for SQLite compatibility
    op.add_column('users', sa.Column('last_credit_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_credit_reset')
    # ### end Alembic commands ###
